language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t unclebae/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true unclebae/docker-react-test npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-103382364946
  bucket_path: "docker-react-test"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

#  DockerReactTest-env.eba-gjapddkc.ap-northeast-2.elasticbeanstalk.com